INSERT INTO `page` (`ID_page`, `modul`, `typ`, `prava`, `nazev`) VALUES
(1, 'login', 'zobraz', 'vsichni', 'Login'),
(2, 'materialy', 'zobraz', 'vsichni', 'Zobrazit studijní materiály'),
(6, 'materialy', 'vloz', 'ucitel', 'Pøidání studijních materiálù'),
(7, 'materialy', 'vymaz', 'ucitel', 'Mazání studijních materiálù'),
(8, 'materialy', 'uprav', 'ucitel', 'Editace studijních materiálù'),
(9, 'materialy', 'zobraz', 'vsichni', 'Zobrazení studijních materiálù'),
(10, 'predmet', 'vloz', 'ucitel', 'Pøidání pøedmìtu'),
(11, 'predmet', 'vymaz', 'ucitel', 'Mazání pøedmìtu'),
(12, 'predmet', 'uprav', 'ucitel', 'Editace pøedmìtu'),
(13, 'predmet', 'zobraz', 'vsichni', 'Zobrazení pøedmìtu'),
(14, 'rozvrh', 'vloz', 'admin', 'Pøidání rozvrhu'),
(15, 'rozvrh', 'vymaz', 'admin', 'Mazání rozvrhu'),
(16, 'rozvrh', 'uprav', 'admin', 'Editace rozvrhu'),
(17, 'rozvrh', 'zobraz', 'vsichni', 'Zobrazení rozvrhu'),
(18, 'ucebny', 'vloz', 'admin', 'Pøidání uèebny'),
(19, 'ucebny', 'vymaz', 'admin', 'Mazání uèebny'),
(20, 'ucebny', 'uprav', 'admin', 'Editace uèebny'),
(21, 'ucebny', 'zobraz', 'vsichni', 'Zobrazení uèebny'),
(22, 'rozvrhzalozeni', 'vloz', 'admin', 'Pøidání rozvrhu'),
(23, 'rozvrhzalozeni', 'vymaz', 'admin', 'Mazání rozvrhu'),
(24, 'rozvrhzalozeni', 'uprav', 'admin', 'Editace rozvrhu'),
(25, 'rozvrhzalozeni', 'zobraz', 'ucitel', 'Zobrazení rozvrhu'),
(26, 'rozvrhprohlizeni', 'vloz', 'ucitel', 'Pøidání rozvrhu'),
(27, 'rozvrhprohlizeni', 'vymaz', 'ucitel', 'Mazání rozvrhu'),
(28, 'rozvrhprohlizeni', 'uprav', 'ucitel', 'Editace rozvrhu'),
(29, 'rozvrhprohlizeni', 'zobraz', 'vsichni', 'Zobrazení rozvrhu'),
(30, 'uzivatele', 'vloz', 'admin', 'Pøidání uživatele'),
(31, 'uzivatele', 'vymaz', 'admin', 'Mazání uživatele'),
(32, 'uzivatele', 'uprav', 'admin', 'Editace uživatele'),
(33, 'uzivatele', 'zobraz', 'vsichni', 'Zobrazení uživatele'),
(38, 'ucebnytypy', 'vloz', 'admin', 'Pøidání typu uèebny'),
(39, 'ucebnytypy', 'vymaz', 'admin', 'Mazání typu uèebny'),
(40, 'ucebnytypy', 'uprav', 'admin', 'Editace typu uèebny'),
(41, 'ucebnytypy', 'zobraz', 'ucitel', 'Zobrazení typu uèebny'),
(42, 'zkousky', 'zobraz', 'vsichni', 'Výpis zkoušek'),
(43, 'zkousky', 'uprav', 'ucitel', 'Známkování'),
(44, 'zkousky', 'vymaz', 'ucitel', 'Mazání zkoušky'),
(45, 'zkousky', 'vloz', 'ucitel', 'Pøidání zkoušky');